<Instrucao@MDScreen>
    MDBoxLayout:
        orientation: "vertical"
        MDLabel:
            id: text_instr
            text:""
            halign: "center"
            font_size: 20

        MDFillRoundFlatButton:
            text: "Iniciar Teste"
            md_bg_color: "#9999ff"
            text_color: "black"
            font_size: 30
            pos_hint: {"center_x": .5, "center_y": .5}
            size_hint: .4, 0.10
            on_release: app.mudar_tela("perguntas")